// Generated by Wrangler by running `wrangler types`

interface Env {
	EVOLUTION_AGENT: DurableObjectNamespace<import("./evolution-agent-simple").EvolutionAgent>;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
}
